
site_name: "Formula Trinity Autonomous Wiki"
site_url: "https://docs.formulatrinity.ie"

theme:
  name: material
  logo: media/FT_Logo.png
  favicon: media/FT_Logo.png
  icon:
    logo: null     # <- prevent book icon fallback
  features:
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.footer  
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - content.status

  # custom_dir: docs/overrides

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: red         # pick your color
    accent: red
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: red
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html 
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: custom            # timeago | date | datetime | iso_date | iso_datetime | custom
      custom_format: "%b %d, %Y"   # e.g. "Oct 17, 2025"
      timezone: Europe/Dublin
      locale: en
    

nav: # This is the structure of the sidebar
  - Home: index.md
  - Hall of Fame: hall_of_fame.md
  - Departments:
      - Perception:
            - Overview: departments/perception/overview.md
            - Theory: departments/perception/theory.md
            - LiDAR Only Solution: departments/perception/clustering_algo.md
            - Calibration: departments/perception/calibration.md
            - Debugging: departments/perception/debugging.md
      - State Estimation:
            - Overview: departments/state_estimation/overview.md
            - Theory: departments/state_estimation/theory.md
      - Path Planning:
            - Overview: departments/path_planning/overview.md
            - Theory: departments/path_planning/theory.md
      - Control:
            - Overview: departments/control/overview.md
            - Theory: departments/control/theory.md
            - Pure Pursuit: departments/control/pure_pursuit.md
            - Pure Pursuit Callback: departments/control/pure_pur_callback.md
            - Velocity Control: departments/control/velocity_control.md
            - PID Tuning: departments/control/pid_tuning.md
      - Hardware:
            - Overview: departments/hardware/overview.md
            - Electronics:
                  - Electronics Overview: departments/hardware/electronics/electronics_overview.md
                  - Jetson Nano: departments/hardware/electronics/jetson_nano.md
                  - Microcontrollers: departments/hardware/electronics/microcontrollers.md
            - Mechanical:
                  - Mechanical Overview: departments/hardware/mechanical/mechanical_overview.md
                  - Lunchy: departments/hardware/mechanical/lunchy.md
                  - Modem: departments/hardware/mechanical/modem.md
          
  - Resources:
      - General Competition Info: resources/competition.md
      - General Git Info: resources/git.md
      - General SSH Resources: resources/ssh.md
      - General ROS2 Resources: resources/ros2.md
      - General Python Resources: resources/python.md
      - General C++ Resources: resources/cpp.md
      - General Linux Resources: resources/linux.md
      - The ROS2 Visualization Stack RVIZ2: resources/rviz2.md
      - The ROS2 Transforms Library (TF2): resources/tf2.md
      - EUFS Sim: resources/eufs_sim.md
      - IPG CarMaker: resources/ipg_carmaker.md
      - Ros Can: resources/ros_can.md
      - Why the F*ck is The Car Not Moving: resources/why_is_car_not_moving.md
      - Other Relevant Sites: resources/relevant.md

  - Tutorials:
      - Getting Started Guide: tutorials/Getting_started.md
      - Cutting Bags Down to Size: tutorials/cutting_bags.md
      - Competition Launch Scripts; Configuration, Setup and Running them: tutorials/comp_launch_scripts.md
      - Reducing Boot Time: tutorials/reducing_boot_time.md
      - Running Code on Linux that are not Ubuntu: tutorials/run_code_not_ubuntu.md
      - Path Planning Tutorial (Getting Started on ROS) (Kind of Deprecated): tutorials/path_planning_tutorial.md
      - How to RDP into the FTA PC: tutorials/rdp_to_fta_pc.md
      - How to SSH into the FTA Pc: tutorials/ssh_to_fta_pc.md
      - Python to C++: tutorials/python_to_cpp.md
      - LiDAR Setup: tutorials/lidar_setup.md
      - YOLO Training: tutorials/yolo_training.md
      - Webpage Setup: tutorials/webpage_setup.md

  - Equipment:
      - ADS-DV Vehicle: equipment/ads_dv.md
      - Jetson Orin: equipment/jetson_orin.md
      - Velodyne LiDAR: equipment/velodyne.md
      - ZED2 Camera: equipment/zed2.md
      - Jetson Nano: equipment/jetson_nano.md
      - Livox Avia: equipment/livox_avia.md    

  - Software Stack:
      - Time Synchronization: Software Stack/Time_sync.md

  - Guidelines:
      - Coding: guidelines/coding.md
      - Documentation: guidelines/documentation.md
      - Development Best Practices: guidelines/development_best_practices.md
      - Troubleshooting: guidelines/troubleshooting.md

  - Miscellaneous:
      - Feedback: miscellaneous/feedback.md

extra_css:
  - overrides/styles.css

